import pandas as pd
import matplotlib.pyplot as plt

# 1. Load both data files generated by your C programs
try:
    df_non = pd.read_csv("two_walkers_correlation.csv")
    df_int = pd.read_csv("Interacting_correlations.csv")
except FileNotFoundError as e:
    print(f"Error: {e.filename} was not found. Make sure to run both C executables first!")
    exit()

# Extract Non-Interacting columns
steps_non = df_non['Step'].values
mean_x1_non = df_non['MeanX1'].values
mean_x2_non = df_non['MeanX2'].values
mean_x1_x2_non = df_non['MeanX1X2'].values
correlation_non = df_non['Correlation'].values

# Extract Interacting columns
steps_int = df_int['Step'].values
mean_x1_int = df_int['MeanX1'].values
mean_x2_int = df_int['MeanX2'].values
mean_x1_x2_int = df_int['MeanX1X2'].values
correlation_int = df_int['Correlation'].values

# 2. Setup a 2x2 multi-plot layout canvas (2 rows, 2 columns)
fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(15, 10))


# ROW 1: NON-INTERACTING WALKERS (3i Baseline)
# Top-Left: Individual and Joint Expectation Values
ax1.plot(steps_non, mean_x1_non, label='$\\langle x_1 \\rangle$ (Walker 1)', color='blue', alpha=0.7)
ax1.plot(steps_non, mean_x2_non, label='$\\langle x_2 \\rangle$ (Walker 2)', color='teal', alpha=0.7)
ax1.plot(steps_non, mean_x1_x2_non, label='$\\langle x_1 x_2 \\rangle$ (Joint Product)', color='purple', alpha=0.7)
ax1.axhline(0, color='black', linestyle='--', lw=1, alpha=0.5)
ax1.set_title('Non-Interacting: Expectation Values vs Time')
ax1.set_xlabel('Step Number ($t$)')
ax1.set_ylabel('Position / Product Value')
ax1.legend()
ax1.grid(True, alpha=0.3)

# Top-Right: Correlation Term
ax2.plot(steps_non, correlation_non, label='Simulated Correlation', color='crimson', lw=2)
ax2.axhline(0, color='black', linestyle='--', lw=1.5, alpha=0.5)
ax2.set_title('Non-Interacting: Statistical Correlation')
ax2.set_xlabel('Step Number ($t$)')
ax2.set_ylabel('$\\langle x_1 x_2 \\rangle - \\langle x_1 \\rangle\\langle x_2 \\rangle$')
ax2.legend()
ax2.grid(True, alpha=0.3)


# ROW 2: INTERACTING WALKERS (3ii Exclusions)
# Bottom-Left: Individual and Joint Expectation Values
ax3.plot(steps_int, mean_x1_int, label='$\\langle x_1 \\rangle$ (Walker 1)', color='blue', alpha=0.7)
ax3.plot(steps_int, mean_x2_int, label='$\\langle x_2 \\rangle$ (Walker 2)', color='teal', alpha=0.7)
ax3.plot(steps_int, mean_x1_x2_int, label='$\\langle x_1 x_2 \\rangle$ (Joint Product)', color='purple', alpha=0.7)
ax3.axhline(0, color='black', linestyle='--', lw=1, alpha=0.5)
ax3.set_title('Interacting: Expectation Values vs Time')
ax3.set_xlabel('Step Number ($t$)')
ax3.set_ylabel('Position / Product Value')
ax3.legend()
ax3.grid(True, alpha=0.3)

# Bottom-Right: Correlation Term
ax4.plot(steps_int, correlation_int, label='Simulated Correlation', color='crimson', lw=2)
ax4.axhline(0, color='black', linestyle='--', lw=1.5, alpha=0.5)
ax4.set_title('Interacting: Statistical Correlation')
ax4.set_xlabel('Step Number ($t$)')
ax4.set_ylabel('$\\langle x_1 x_2 \\rangle - \\langle x_1 \\rangle\\langle x_2 \\rangle$')
ax4.legend()
ax4.grid(True, alpha=0.3)

# Clean up layout structure and render everything
plt.tight_layout()
plt.show()
